# Generated by Django 2.0.4 on 2018-04-23 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idcarddetails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharCardPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharPhoto', models.ImageField(upload_to=idcarddetails.models.user_aadhar_path)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicensePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivingLicensePhoto', models.ImageField(upload_to=idcarddetails.models.user_drivingLicense_path)),
            ],
        ),
        migrations.CreateModel(
            name='IDCardNumbers',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aadharNumber', models.CharField(max_length=20, unique=True)),
                ('drivingLicenseNumber', models.CharField(max_length=20, unique=True)),
                ('voterCardNumber', models.CharField(max_length=20, unique=True)),
                ('rationCardNumber', models.CharField(max_length=20, unique=True)),
                ('passportNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportPhoto', models.ImageField(upload_to=idcarddetails.models.user_passport_path)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RationCardPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationCardPhoto', models.ImageField(upload_to=idcarddetails.models.user_rationCard_path)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterCardPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterCardPhoto', models.ImageField(upload_to=idcarddetails.models.user_voterCard_path)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drivinglicensephotos',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aadharcardphotos',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
